# Generated by Django 4.2.6 on 2023-11-15 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=100)),
                ('secret', models.CharField(max_length=100)),
                ('file', models.CharField(max_length=60)),
                ('gender', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'buyer_details',
            },
        ),
        migrations.CreateModel(
            name='Listings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('posted_by', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('email', models.CharField(max_length=100)),
                ('img', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'seller_listings',
            },
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=100)),
                ('secret', models.CharField(max_length=100)),
                ('file', models.CharField(max_length=60)),
                ('gender', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'seller_details',
            },
        ),
    ]
